### ISSUE TITLE
Where are the other 2 solar systems?

### ISSUE THREAD

**Issue by MegaPiggy** [ErroneousCreationist/solarneighbourhood#2]
Where is these 2 solar systems?
![image](https://user-images.githubusercontent.com/34462599/161362169-a0a62fba-3c0a-470d-829b-fe20c15c5845.png)

Also, why do the planets and star look different from the photos?
![image](https://user-images.githubusercontent.com/34462599/161371247-2c3e1dbe-ac99-4ca8-b9ae-48ec22cfe233.png)
![image](https://user-images.githubusercontent.com/34462599/161371251-d99f932d-9ef6-4e5a-afc7-399b6bd89a95.png)

**Comment by ErroneousCreationist** [comment]
I was only basing it of the image, and by the time i finished the 3 that are ingame, the planets were kinda boring to explore, and the lower right one was a carbon copy of a different one (star went red to blue). I replaced the lower right one with something else more interesting (spoilers) and the lower left one i never added.

**Comment by MegaPiggy** [comment]
Oh okay. Thank you for answering. It would be cool if you added the lower left one.
